name: CI / Automated build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    # This workflow is only of value to the NeuraLegion/sectester-js-demo-broken-crystals repository
    if: github.repository == 'NeuraLegion/sectester-js-demo-broken-crystals'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install deps in quiet mode
        run: npm ci -q

      - name: Lint application
        run: npm run lint

      - name: Check formatting
        run: npm run format
